Repository eoscostarica/guias.eoscostarica.io, pull requests merged in 2020-06, with the labels that each got.

#29 docs(README): se añade un tutorial donde se definen los pasos a seguir para correr el sitio de forma local desde windows 10
  README.md
  website/package-lock.json
Labels: documentation

#31 Update docs
  docs/aprender-eosio/uso-de-recursos.md
  website/sidebars.json
Labels: content, documentation

#44 add code block style
  docs/aprender-eosio/uso-de-recursos.md
Labels: bug

#47 docs update with new content
  docs/aprender-eosio/como-iniciar.md
  docs/aprender-eosio/instalacion-de-nodos.md
  docs/aprender-eosio/linea-de-comando.md
  docs/aprender-eosio/llaves-privadas.md
  docs/aprender-eosio/mecanismo-de-consenso.md
  website/sidebars.json
Labels: content, documentation

#60 Re arrange videos
  docs/aprender-eosio/cadena-de-bloques-eos.md
  docs/aprender-eosio/contratos-inteligentes.md
  docs/aprender-eosio/cpp-moderno.md
  docs/aprender-eosio/cuentas-permisos.md
  docs/aprender-eosio/desarrollo-de-dapps.md
  docs/aprender-eosio/devops.md
  docs/aprender-eosio/funciones-importantes.md
  docs/aprender-eosio/mecanismo-de-consenso.md
  docs/aprender-eosio/protocolo-eosio.md
  docs/aprender-eosio/redes-eosio.md
  docs/aprender-eosio/software-eosio.md
  docs/aprender-eosio/uso-de-recursos.md
  website/sidebars.json
Labels: content
