Repository eoscostarica/guias.eoscostarica.io, pull requests merged in 2022-07, with the labels that each got.

#346 pow vs pos vs dpos #318
  docs/aprender-eosio/mecanismo-de-consenso.md
  docs/herramientas/pow-vs-pos-vs-dpos.md
  sidebars.js
Labels: español

#343 Add to developers guidelines investigation IPFS
  docs/interplanetary-file-system.md
  sidebars.js
Labels: documentation, español

#348 feat(common): Adding above consensus mechanisms
  docs/mecanismos-de-consenso-blockchain.md
  sidebars.js
Labels: español

#352 feat(frontend): Add information about Blue Papers #385
  docs/aprender-eosio/fundacion-red-eos.md
  sidebars.js
Labels: English and Spanish

#366 chore(frontend): improve meta description
  docusaurus.config.js
  src/pages/index.js
Labels: español

#364 feat(frontend): Adding useful link ESP #495 #500
  docs/aprender-eosio/contratos-inteligentes.md
  docs/comunidad/enlaces-utiles.md
  docs/herramientas/ejemplos-contratos-inteligentes-eosio.md
  sidebars.js
Labels: English and Spanish

#373 fix(bug): Change to correct function ESP #516
  docusaurus.config.js
  src/pages/index.js
Labels: English and Spanish

#375 fix(frontend): Adding command slash on config ESP #465
  docusaurus.config.js
Labels: English and Spanish

#382 refactor(frontend): New descriptive hyperlink ESP #523
  docs/aprender-eosio/componentes-eosio.md
  docs/aprender-eosio/contratos-ricardianos.md
  docs/aprender-eosio/desarrollo-de-dapps.md
  docs/aprender-eosio/funciones-importantes.md
  docs/aprender-eosio/fundacion-red-eos.md
  docs/aprender-eosio/uso-de-recursos.md
  docs/boilerplate-para-backend.md
  docs/comunidad/publicaciones-blog.md
  docs/devops.md
  docs/herramientas-para-desarrolladores.md
  docs/herramientas/plantilla-readme.md
  docs/herramientas/preguntas-frecuentes.md
  docs/material-ui.md
  docs/mecanismos-de-consenso-blockchain.md
  docs/pautas-para-codigo-abierto.md
  docs/tutoriales/docker.md
  docs/tutoriales/guia-github.md
  docs/tutoriales/guia-markdown.md
  docs/tutoriales/instalacion-de-nodos.md
  docs/tutoriales/instalacion-de-red-privada.md
  docs/tutoriales/kubernetes.md
  docs/tutoriales/llaves-github.md
  docs/tutoriales/tutorial-react.md
Labels: English and Spanish

#385 docs(frontend): add blog link to security page
  docs/aprender-eosio/seguridad-blockchain.md
Labels: español

#388 feat(frontend): Improve homepage styles ESP #439
  src/css/homepage.css
  src/pages/CustomArticle/CustomArticle.js
  src/pages/CustomArticle/index.js
  src/pages/CustomArticle/styles.js
  src/pages/heroSection/ImagesCarousel.js
  src/pages/heroSection/index.js
  src/pages/heroSection/styles.js
  src/pages/index.js
  src/pages/startResource/CustomCard.js
  src/pages/startResource/index.js
  src/pages/startResource/styles.js
  static/img/cards-icons/EOS-Previews-2.webp
  static/img/cards-icons/Hero-1.webp
  static/img/cards-icons/Hero-2.webp
  static/img/cards-icons/blog1.webp
  static/img/cards-icons/blog2.webp
  static/img/cards-icons/blog3.webp
  static/img/cards-icons/community.svg
  static/img/cards-icons/guidelines.svg
  static/img/cards-icons/icons-eosio.svg
  static/img/cards-icons/icons-opensource.svg
  static/img/cards-icons/learneosio.svg
  static/img/cards-icons/tools.svg
  static/img/cards-icons/tutorials.svg
Labels: English and Spanish

#394 Feat/improve homepage styles jm 439
  docusaurus.config.js
  src/css/custom.css
  src/css/homepage.css
  src/pages/CustomArticle/CustomArticle.js
  src/pages/CustomArticle/index.js
  src/pages/CustomArticle/styles.js
  src/pages/heroSection/ImagesCarousel.js
  src/pages/heroSection/index.js
  src/pages/heroSection/styles.js
  src/pages/index.js
  src/pages/startResource/CustomCard.js
  src/pages/startResource/index.js
  src/pages/startResource/styles.js
  static/img/cards-icons/Hero-3.webp
Labels: español

#395 fix(frontend):Working without delay ESP #544
  docusaurus.config.js
  src/css/homepage.css
  src/pages/index.js
Labels: español

#396 refactor(homePage): New heroSection images ESP #546
  static/img/cards-icons/Hero-1.webp
  static/img/cards-icons/Hero-2.webp
  static/img/cards-icons/Hero-3.webp
Labels: español

#392 fix(frontend): relsolve errors in markdown files
  docs/aprender-eosio/cadena-de-bloques-eos.md
  docs/aprender-eosio/contratos-inteligentes.md
  docs/aprender-eosio/cuentas-permisos.md
  docs/aprender-eosio/desarrollo-de-dapps.md
  docs/aprender-eosio/mecanismo-de-consenso.md
  docs/aprender-eosio/nft-en-eosio.mdx
  docs/aprender-eosio/seguridad-blockchain.md
  docs/aprender-eosio/uso-de-recursos.md
  docs/comunidad/redes-eosio.md
  docs/devops.md
  docs/herramientas-para-desarrolladores-ux-ui.md
  docs/herramientas-para-desarrolladores.md
  docs/interplanetary-file-system.md
  docs/mecanismos-de-consenso-blockchain.md
  docs/metodologia-vuelos.md
  docs/metodologias-agiles.md
  docs/pautas-para-codigo-abierto.md
  docs/proyectos-de-codigo-abierto.mdx
  docs/tutoriales/contrato-hola-mundo.md
  docs/tutoriales/cpp-moderno.md
  docs/tutoriales/guia-markdown.md
  docs/tutoriales/tutorial-flujo-trabajo-git.md
  docs/tutoriales/tutorial-react.md
  src/components/ProjectContainer/DisplayImages.js
Labels: español
